name: Daily Grant Scraper

on:
  schedule:
    - cron: "0 5 * * *"  # Runs daily at 5:00 AM UTC
  workflow_dispatch:      # Allows manual trigger from GitHub

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BASE_URL: ${{ secrets.BASE_URL }}

      - name: Commit and push updated CSV
        run: |
          git config --global user.name "cfp-bot"
          git config --global user.email "cfp-bot@example.com"
          git add grants_database.csv
          git commit -m "Auto update: scrape $(date -u +%Y-%m-%d)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

